rh_offset: "0.0"
rh_min_change: "2.0"
temp_offset: "0.0"
temp_min_change: "0.2"
max_skip_cycles: "10"
lp_poll_interval_sec: "20"
heater_period_minutes: "1440"
heater_high_rh_trigger_minutes: "60"
read_battery_via_adc: "true"
battery_divider_r_vbat_ohm: "200200"
battery_divider_r_gnd_ohm: "201700"

