#include "lp_sensor_core.h"
#include "shared_layout.h"

#include <esp_log.h>
#include <esp_sleep.h>
#include <esp_pm.h>
#include <freertos/FreeRTOS.h>
#include <freertos/event_groups.h>
#include "ulp_lp_core.h"
#include "lp_core_i2c.h"

// Auto-generated by ulp_embed_binary() from lp_core/main.cpp's compiled ELF; declares
// ulp_g_shared (the shared struct's storage, typed as uint32_t[]) among other symbols.
#include "lp_core_lp_sensor_core.h"

static const char *TAG = "lp_sensor_core";

extern const uint8_t lp_core_lp_sensor_core_bin_start[] asm("_binary_lp_core_lp_sensor_core_bin_start");
extern const uint8_t lp_core_lp_sensor_core_bin_end[]   asm("_binary_lp_core_lp_sensor_core_bin_end");

// Set (from the light-sleep exit callback below) when a light sleep was ended by the LP
// core's ULP wakeup source, so lp_sensor_core_wait_for_wake() can return early instead of
// waiting out its full timeout.
static const EventBits_t BIT_EARLY_WAKE = BIT0;
static EventGroupHandle_t s_wake_eg = NULL;

// Runs from IDLE task context after every automatic light-sleep attempt (CONFIG_PM_
// LIGHT_SLEEP_CALLBACKS) -- see esp_pm_light_sleep_register_cbs()'s doc comment: no blocking
// calls allowed here, hence the ISR-safe (deferred, non-blocking) set-bits call even though
// this isn't a genuine ISR.
static esp_err_t on_light_sleep_exit(int64_t sleep_time_us, void *arg)
{
    (void)sleep_time_us;
    (void)arg;
    if (esp_sleep_get_wakeup_causes() & BIT(ESP_SLEEP_WAKEUP_ULP))
        xEventGroupSetBitsFromISR(s_wake_eg, BIT_EARLY_WAKE, NULL);
    return ESP_OK;
}

esp_err_t lp_sensor_core_init(const lp_sensor_core_config_t *config)
{
    // SHT4x is wired to GPIO6/GPIO7 -- the SoC-fixed LP_I2C pins, not configurable.
    // Standard mode (100kHz), not the LP_CORE_I2C_DEFAULT_CONFIG() default of 400kHz:
    // this board's GPIO6/7 castellated-pad connection has a history of marginal signal
    // integrity (see the migration plan's "Hardware prerequisite" section), and 100kHz
    // gave reliably clean reads in earlier HP-side bring-up where 1MHz didn't.
    lp_core_i2c_cfg_t i2c_cfg = LP_CORE_I2C_DEFAULT_CONFIG();
    i2c_cfg.i2c_timing_cfg.clk_speed_hz = 100000;
    const esp_err_t i2c_err = lp_core_i2c_master_init(LP_I2C_NUM_0, &i2c_cfg);
    if (i2c_err != ESP_OK) {
        ESP_LOGE(TAG, "lp_core_i2c_master_init failed: %d", i2c_err);
        return i2c_err;
    }

    const esp_err_t load_err = ulp_lp_core_load_binary(
        lp_core_lp_sensor_core_bin_start,
        lp_core_lp_sensor_core_bin_end - lp_core_lp_sensor_core_bin_start);
    if (load_err != ESP_OK) {
        ESP_LOGE(TAG, "ulp_lp_core_load_binary failed: %d", load_err);
        return load_err;
    }

    // ulp_lp_core_load_binary() just zeroed the whole shared region and the LP timer
    // hasn't started yet (that's lp_sensor_core_start(), called after this returns), so
    // there's no concurrent LP-side writer here -- a plain write, no seqlock needed.
    lp_shared_state_t *shared = (lp_shared_state_t *)ulp_g_shared;
    shared->temp_offset_c = config->temp_offset_c;
    shared->temp_min_change_c = config->temp_min_change_c;
    shared->rh_offset_pct = config->rh_offset_pct;
    shared->rh_min_change_pct = config->rh_min_change_pct;
    shared->max_skip_cycles = config->max_skip_cycles;

    const esp_err_t wakeup_err = esp_sleep_enable_ulp_wakeup();
    if (wakeup_err != ESP_OK)
        return wakeup_err;

    // Backs lp_sensor_core_wait_for_wake() -- see on_light_sleep_exit() above. Requires
    // CONFIG_PM_LIGHT_SLEEP_CALLBACKS=y (sdkconfig.defaults).
    s_wake_eg = xEventGroupCreate();
    if (!s_wake_eg) {
        ESP_LOGE(TAG, "xEventGroupCreate failed");
        return ESP_ERR_NO_MEM;
    }

    esp_pm_sleep_cbs_register_config_t cbs_conf = {
        .exit_cb = on_light_sleep_exit,
    };
    const esp_err_t cb_err = esp_pm_light_sleep_register_cbs(&cbs_conf);
    if (cb_err != ESP_OK) {
        ESP_LOGE(TAG, "esp_pm_light_sleep_register_cbs failed: %d", cb_err);
        return cb_err;
    }

    return ESP_OK;
}

esp_err_t lp_sensor_core_start(uint32_t poll_interval_us)
{
    ulp_lp_core_cfg_t cfg = {
        .wakeup_source = ULP_LP_CORE_WAKEUP_SOURCE_LP_TIMER,
        .lp_timer_sleep_duration_us = poll_interval_us,
    };
    return ulp_lp_core_run(&cfg);
}

void lp_sensor_core_get_state(lp_shared_state_t *out)
{
    // ulp_g_shared is generated as a flat uint32_t[] blob; reinterpret its address as
    // the real struct both sides agree on (see shared_layout.h). volatile so the compiler
    // can't hoist/cache result_seq across retry iterations -- it changes asynchronously,
    // written by the LP core, not by anything the HP-side compiler can see.
    const volatile lp_shared_state_t *shared = (const volatile lp_shared_state_t *)ulp_g_shared;

    for (int attempt = 0; attempt < 10; attempt++) {
        const uint32_t seq_before = shared->result_seq;
        if (seq_before & 1)
            continue; // LP core is mid-write; retry immediately without copying
        *out = *(const lp_shared_state_t *)shared;
        const uint32_t seq_after = shared->result_seq;
        if (seq_before == seq_after)
            return; // clean read
    }
    // Fell through 10 straight torn reads (should never happen at this poll cadence) --
    // *out holds whatever the last attempt captured; caller sees a possibly-stale but not
    // torn snapshot.
}

void lp_sensor_core_ack_delivered(float temp_c, float hum_pct)
{
    // Values first, then the change-counter last -- see the ordering note on hp_ack_seq in
    // shared_layout.h. volatile for the same reason as lp_sensor_core_get_state(): these
    // fields are read asynchronously by the LP core, not by anything the HP-side compiler
    // can see, so the compiler must not reorder or elide these stores.
    volatile lp_shared_state_t *shared = (volatile lp_shared_state_t *)ulp_g_shared;
    shared->hp_acked_temp_c = temp_c;
    shared->hp_acked_hum_pct = hum_pct;
    shared->hp_ack_seq = shared->hp_ack_seq + 1;
}

bool lp_sensor_core_wait_for_wake(uint32_t timeout_ms)
{
    if (!s_wake_eg)
        return false;  // lp_sensor_core_init() hasn't run (or failed) -- nothing to wait on

    const EventBits_t bits = xEventGroupWaitBits(
        s_wake_eg, BIT_EARLY_WAKE, pdTRUE, pdFALSE, pdMS_TO_TICKS(timeout_ms));
    return (bits & BIT_EARLY_WAKE) != 0;
}
