#!/bin/bash
set -e

# Sets up PATH with all versioned ESP-IDF tool paths (cmake, toolchain, python env, etc.)
source /opt/esp/idf/export.sh 2>/dev/null

# Allow git to operate in bind-mounted workspace (owned by host UID, not container UID)
git config --global --add safe.directory '*'

# Generate env file for all bash shells:
#   interactive terminals  → sourced via ~/.bashrc
#   non-interactive shells → sourced via BASH_ENV (set in devcontainer.json remoteEnv)
cat > /usr/local/bin/idf-env.sh <<EOF
# Auto-generated by .devcontainer/setup.sh — do not edit
export PATH="$PATH"
export IDF_PYTHON_ENV_PATH="$IDF_PYTHON_ENV_PATH"
export ESP_IDF_VERSION="$ESP_IDF_VERSION"
EOF

echo "source /usr/local/bin/idf-env.sh" >> ~/.bashrc

# Write versioned tool paths to VS Code machine settings (read at server startup)
mkdir -p ~/.vscode-server/data/Machine
cat > ~/.vscode-server/data/Machine/settings.json <<EOF
{
  "idf.pythonBinPath": "$(which python)",
  "idf.customExtraVars": {
    "IDF_PYTHON_ENV_PATH": "$IDF_PYTHON_ENV_PATH"
  }
}
EOF
