#!/bin/bash
set -e

# esp-matter image layout: ESP-IDF and esp-matter both live under /opt/espressif.
# Source both so PATH/env include idf.py, the toolchain, and the esp-matter tools.
source "$IDF_PATH/export.sh" 2>/dev/null
source "$ESP_MATTER_PATH/export.sh" 2>/dev/null

# Allow git to operate in bind-mounted workspace (owned by host UID, not container UID)
git config --global --add safe.directory '*'

# Generate env file for all bash shells:
#   interactive terminals  → sourced via ~/.bashrc
#   non-interactive shells → sourced via BASH_ENV (set in devcontainer.json remoteEnv)
cat > /usr/local/bin/idf-env.sh <<EOF
# Auto-generated by .devcontainer/setup.sh — do not edit
export PATH="$PATH"
export IDF_PYTHON_ENV_PATH="$IDF_PYTHON_ENV_PATH"
export ESP_IDF_VERSION="$ESP_IDF_VERSION"
export ESP_MATTER_PATH="$ESP_MATTER_PATH"
EOF

echo "source /usr/local/bin/idf-env.sh" >> ~/.bashrc

# Write versioned tool paths to VS Code machine settings (read at server startup)
mkdir -p ~/.vscode-server/data/Machine
cat > ~/.vscode-server/data/Machine/settings.json <<EOF
{
  "idf.pythonBinPath": "$(which python)",
  "idf.customExtraVars": {
    "IDF_PYTHON_ENV_PATH": "$IDF_PYTHON_ENV_PATH"
  }
}
EOF
