#!/bin/bash
set -e

# Sets up PATH with all versioned ESP-IDF tool paths (cmake, toolchain, python env, etc.)
source /opt/esp/idf/export.sh 2>/dev/null

# Allow git to operate in bind-mounted workspace (owned by host UID, not container UID)
git config --global --add safe.directory '*'

# udevadm is required by the ESP-IDF VS Code extension's serial port picker
# (it shells out to `udevadm info -e` to enumerate/describe devices); the
# base image ships libudev1 but not the udev package itself.
if ! command -v udevadm >/dev/null 2>&1; then
  apt-get update
  apt-get install -y --no-install-recommends udev
  rm -rf /var/lib/apt/lists/*
fi

# Generate env file for all bash shells:
#   interactive terminals  → sourced via ~/.bashrc
#   non-interactive shells → sourced via BASH_ENV (set in devcontainer.json remoteEnv)
cat > /usr/local/bin/idf-env.sh <<EOF
# Auto-generated by .devcontainer/setup.sh — do not edit
export PATH="$PATH"
export IDF_PYTHON_ENV_PATH="$IDF_PYTHON_ENV_PATH"
export ESP_IDF_VERSION="$ESP_IDF_VERSION"
EOF

echo "source /usr/local/bin/idf-env.sh" >> ~/.bashrc

# Write versioned tool paths to VS Code machine settings (read at server startup)
mkdir -p ~/.vscode-server/data/Machine
cat > ~/.vscode-server/data/Machine/settings.json <<EOF
{
  "idf.pythonBinPath": "$(which python)",
  "idf.customExtraVars": {
    "IDF_PYTHON_ENV_PATH": "$IDF_PYTHON_ENV_PATH"
  }
}
EOF

# Python deps of the project's own scripts that the IDF python env lacks
# (tools/ota_push.py). Installed into the IDF env, which is `python3` on PATH.
python -m pip install --quiet paho-mqtt
